### PR TITLE
Binary patching of STM based targets broken

### LINKED ISSUE #2293: 3.3 rc2 flash successful but can't bind
## Current Behavior

Updated r9m accst and r9mm accst from 3.2 to 3.3 RC2 using 1.6.0 RC1 configurator. Both successful but will not bind. 
## Steps to Reproduce
Flashed both tx and rx with 3.3 rc2 using 1.6.0 rc1 configurator multiple times, all successfull but no bind. 
Flashed both back to 3.2 and success and is bound.
Flashed tx to 3.3 rc2 then flashed a new BetaFPV Super D 915 with 3.3 RC 2, flash successful but no bind. Repeat flash 2 more times with same result. 
Flashed tx back to 3.2 and it binds. 
Tx on 3.2 and rx on 3.3RC2 binds

1.

2.

3.

4.

## Your Environment

- TX hardware: Frsky r9M ACCST
- RX hardware: BetaFPV Super D 915
- Handset model: Radiomaster TX16
- OpenTX version (including nightly number) Opentx 2.3.14
- ExpressLRS version (TX & RX MUST MATCH): 3.3 RC2
- Packet Rate:
- Telemetry Ratio:
- user_defines:

### PR DESCRIPTION
**Pull request by pkendall64**
# Problem
At some stage the during the development cycle the `firmwareOptions` singleton structure, which contains all the "compile time" options sort of broke in an unexpected way.
The UID which is placed into the structure was duplicated to 2 positions in the resulting firmware, and so when the patching happened it only updated the one place, which tuned out not to be the place that it was required.

# Solution
Change the `firmwareOptions` to be a RAM based structure and copy the flashed version to RAM during initialisation.
This forces there to be only a single copy of the firmware options available at runtime i.e. the one on RAM.

This does increase the RAM requirement ever so slightly, but hey, we're still under 25% used.

Fixes #2293

# Testing
Build the firmware R9M target with an empty set of defines.
Then run this command to put your bind-phrase in.
```bash
python3 python/binary_configurator.py --buzzer-mode default-tune --tx --phrase my-phrase .pio/build/Frsky_TX_R9M_via_stock_BL/firmware.elrs
```
Select the option for R9M target. Copy the firmware.elrs file to the radio and flash via EdgeTX stock mode and test.

### CODE REVIEW

File: src/lib/OPTIONS/options.h [hunk 1]
```diff
@@ -69,8 +69,9 @@ extern uint32_t flash_discriminator;
 #include "EspFlashStream.h"
 extern bool options_HasStringInFlash(EspFlashStream &strmFlash);
 #else
-extern const firmware_options_t firmwareOptions;
+extern firmware_options_t firmwareOptions;
```
Comment (cruwaller) [inline src/lib/OPTIONS/options.h:72]: extern for `static` variable?

Comment (cruwaller) [reply src/lib/OPTIONS/options.h:72]: Sorry... Renamed 🤦

**Comment by SunjunKim** [comment]
I confirm it patches the binary with my binding UI correctly.
image

Flashing this to a R9M successfully connected to other 900M rx.

**Review by SunjunKim — APPROVED** [review]

**Review by deadbytefpv — APPROVED** [review]
Tested with an R9M 2019. Syncs now with 900MHz Receivers.
