### PR TITLE
Separate FIFO locations for TX & RX on SX1280

### LINKED ISSUE #3617: SuperP 14CH RX ELRS 2.4G Receiver reset causes bad channel output
## Current Behavior

We are using a SuperP 14CH RX ELRS 2.4G receiver (ESP32-based) with a RadioMaster TX16S and RadioMaster Ranger.

During one of our test flights, we observed intermittent link loss (~1-2 seconds). Instead of entering failsafe, the receiver outputs unexpected PWM values, causing erratic servo movement, which resulted in a crash.

This is also visible through mavlink through our telemetry logs:

Image

The orange line is the link quality and the blue are the channel outputs.

## Environment
Receiver firmware: UNIFIED_ESP32_2400_RX 
Version: 4.0.0
Protocol: Mavlink
SBUS failsafe: No Pulses
Target SysID: 1
Source SysID: 255
Tlm Power: 100 mW
Output: 10 channels of PWM (Failsafe position set) and 2 channels of setup serial connections for mavlink

Transmitter firmware: CE_LBT
Version: 4.0.0
Packet rate: 333Hz Full
Telem Radio: 1:2 
Switch Mode: 16ch Rate /2
Model match: Off (ID:12)
TX Power: 100mW
Dynamic Power: Off
Regulatory Domain: 100 mW 2G4 CE LIMIT

## Steps to Reproduce
We were able to reproduce the issue reliably in a controlled environment:

Triggering an ESP32 reset (EN button) on the receiver
In ~20% of cases (1 out of 5):
The receiver outputs a spurious PWM value (~881)

## Possible Solution (Not obligatory)
Changing the packet rate to 100Hz Full and the PWM servo output rate to 50 Hz, the issue seems less probable (1 event after 100 reset events)

### PR DESCRIPTION
**Pull request by pkendall64**
# Problem
On SX1280 receivers, the radio driver was using the same internal packet buffer region for both transmit and receive operations. Under rare conditions this could allow a just-transmitted telemetry payload, such as an OTA LinkStats packet, to be read back through the receive path and misinterpreted as RC data. Because LinkStats and RC packets share the same OTA packet type value; when in MAVLink mode, this could appear on the flight controller as a bogus `RC_CHANNELS_OVERRIDE` frame and would cause a disarm of the craft if using channel-based arming.

# Solution
The SX1280 driver now uses separate FIFO base addresses for transmit and receive. This prevents transmitted telemetry data from being re-read through the RX path and removes the buffer aliasing condition that could cause LinkStats payloads to be decoded as RC data.

# Belt-and-braces
As an additional safeguard, the RX path also validates the radio status returned by `GET_RXBUFFERSTATUS` before reading packet data. The driver only accepts a received packet if the chip reports that it is in RX mode and that data is available for reading.

### CODE REVIEW

**Comment by d-papworth** [comment]
At the request of @pkendall64 after chatting in the ELRS Discord #mavlink-rc channel [](https://discord.com/channels/596350022191415318/1165186741716656230/1495870818297712651) I tested with stock ELRS v4.0 for about 30 min on the bench with multiple channel low (881us) events, then flashed this PR and tested on the bench for about 20 min with no occurrences of the channel low (881us) events, which suggests that the fix applied resolves the issue.

With stock ELRS v4.0
image

With this PR flashed to RX and TX
image

**Comment by pkendall64** [comment]
Thanks @d-papworth

File: src/lib/SX1280Driver/SX1280.cpp [hunk 1]
```diff
@@ -10,6 +10,9 @@ SX1280Driver *SX1280Driver::instance = NULL;
 
 RFAMP_hal RFAMP;
 
+constexpr uint8_t SX1280_TX_BUFFER_BASE = 0x00;
+constexpr uint8_t SX1280_RX_BUFFER_BASE = 0x80;
```
Comment (CapnBry) [inline src/lib/SX1280Driver/SX1280.cpp]: These should be in the SX1280 class or something and not just floating out here in the global namespace non-staticly

File: src/lib/SX1280Driver/SX1280_hal.h [hunk 2]
```diff
@@ -43,7 +43,7 @@ class SX1280Hal
     void ICACHE_RAM_ATTR WriteRegister(uint16_t address, uint8_t *buffer, uint8_t size, SX12XX_Radio_Number_t radioNumber);
     void ICACHE_RAM_ATTR WriteRegister(uint16_t address, uint8_t value, SX12XX_Radio_Number_t radioNumber);
 
-    void ICACHE_RAM_ATTR ReadCommand(SX1280_RadioCommands_t opcode, uint8_t *buffer, uint8_t size, SX12XX_Radio_Number_t radioNumber);
+    uint8_t ICACHE_RAM_ATTR ReadCommand(SX1280_RadioCommands_t opcode, uint8_t *buffer, uint8_t size, SX12XX_Radio_Number_t radioNumber);
```
Comment (CapnBry) [inline src/lib/SX1280Driver/SX1280_hal.h]: Isn't this returning a SX1280_RadioStatus_t set and therefor appropriate to declare that? uint8_t is ambiguous like it could return size or something (and we have no comments so you have to check the impl to know)

**Review by CapnBry — COMMENTED** [review]
I may have come for the FIFO buffer segmentation but I really think the verification but the verification of the chipStatus is an even stronger fix. I believe that also would have solved the old issue where we were getting too many interrupts per period and faux-advancing the nonce

File: src/lib/SX1280Driver/SX1280.cpp (hunk 1 above)
Comment (pkendall64) [reply src/lib/SX1280Driver/SX1280.cpp]: will do

File: src/lib/SX1280Driver/SX1280_hal.h (hunk 2 above)
Comment (pkendall64) [reply src/lib/SX1280Driver/SX1280_hal.h]: done

**Review by CapnBry — APPROVED** [review]
Thanks! Incredible work finding this, it is amazing we've never seen this in testing, and thanks @d-papworth for reporting with all the details.

**Review by mha1 — APPROVED** [review]
6h run yesterday on a SX1280/SX1280 setup woth no obvious issues.
